apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  MONGO_URI: "mongodb://mongodb-service:27017/Mern_project"
  REACT_APP_SERVER_URL: "http://server-service:5000"
  PORT: "5000"
